name: 'ecommerce_dw'

config-version: 2
version: '0.1.0'

profile: 'ecommerce_dw'

analysis-paths: ["analyses"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  ecommerce_dw:    
    # Raw (incremental from staging)
    raw:
      +materialized: incremental
      +on_schema_change: "append_new_columns"
      +schema: raw
      +unique_key: id
    
    # Warehouse (facts and dimensions)
    warehouse:
      +schema: warehouse
      dimensions:
        +materialized: table
      facts:
        +materialized: incremental
        +on_schema_change: "append_new_columns"

snapshots:
  ecommerce_dw:
    +target_schema: snapshots
    +strategy: timestamp
    +unique_key: id
    +updated_at: updated_at
