sources:
  - name: raw_ingest
    description: Raw ingestion tables loaded from data lake with batch_id
    database: warehouse_db
    schema: raw_ingest
    tables:
      - name: users
        description: User profile snapshots by batch
        columns:
          - name: batch_id
            description: Batch ID (YYYYMMDD format)
            data_tests:
              - not_null
          - name: id
            description: User ID
            data_tests:
              - not_null
          - name: name
            description: User name
            data_tests:
              - not_null
          - name: email
            description: User email
            data_tests:
              - not_null
          - name: address
            description: User address
            data_tests:
              - not_null
          - name: created_at
            description: Creation timestamp
            data_tests:
              - not_null
          - name: updated_at
            description: Last update timestamp
            data_tests:
              - not_null
          - name: deleted_at
            description: Deletion timestamp

      - name: products
        description: Product catalog snapshots by batch
        columns:
          - name: batch_id
            description: Batch ID (YYYYMMDD format)
            data_tests:
              - not_null
          - name: id
            description: Product ID
            data_tests:
              - not_null
          - name: name
            description: Product name
            data_tests:
              - not_null
          - name: category
            description: Product category
            data_tests:
              - not_null
          - name: price
            description: Product price
            data_tests:
              - not_null
          - name: created_at
            description: Creation timestamp
            data_tests:
              - not_null
          - name: updated_at
            description: Last update timestamp
            data_tests:
              - not_null
          - name: deleted_at
            description: Deletion timestamp

      - name: orders
        description: Order snapshots by batch
        columns:
          - name: batch_id
            description: Batch ID (YYYYMMDD format)
            data_tests:
              - not_null
          - name: id
            description: Order ID
            data_tests:
              - not_null
          - name: user_id
            description: User who placed the order
            data_tests:
              - not_null
          - name: status
            description: Order status
            data_tests:
              - not_null
              - accepted_values:
                  values: ['pending', 'shipped', 'completed', 'cancelled']
          - name: created_at
            description: Creation timestamp
            data_tests:
              - not_null
          - name: updated_at
            description: Last update timestamp
            data_tests:
              - not_null

      - name: order_items
        description: Order item snapshots by batch
        columns:
          - name: batch_id
            description: Batch ID (YYYYMMDD format)
            data_tests:
              - not_null
          - name: id
            description: Order item ID
            data_tests:
              - not_null
          - name: order_id
            description: Reference to order
            data_tests:
              - not_null
          - name: product_id
            description: Product which was ordered
            data_tests:
              - not_null
          - name: quantity
            description: Order quantity of a product
            data_tests:
              - not_null
