models:
  - name: users
    description: User profile
    columns:
      - name: id
        description: User ID
        data_tests:
          - not_null
          - unique
      - name: name
        description: User name
        data_tests:
          - not_null
      - name: email
        description: User email
        data_tests:
          - not_null
          - unique
      - name: address
        description: User address
        data_tests:
          - not_null
      - name: created_at
        description: Creation timestamp
        data_tests:
          - not_null
      - name: updated_at
        description: Last update timestamp
        data_tests:
          - not_null
      - name: deleted_at
        description: Deletion timestamp

  - name: products
    description: Product catalog
    columns:
      - name: id
        description: Product ID
        data_tests:
          - not_null
          - unique
      - name: name
        description: Product name
        data_tests:
          - not_null
          - unique
      - name: category
        description: Product category
        data_tests:
          - not_null
      - name: price
        description: Product price
        data_tests:
          - not_null
      - name: created_at
        description: Creation timestamp
        data_tests:
          - not_null
      - name: updated_at
        description: Last update timestamp
        data_tests:
          - not_null
      - name: deleted_at
        description: Deletion timestamp

  - name: orders
    description: Orders from main platform
    columns:
      - name: id
        description: Order ID
        data_tests:
          - not_null
          - unique
      - name: user_id
        description: User who placed the order
        data_tests:
          - not_null
      - name: status
        description: Order status
        data_tests:
          - not_null
          - accepted_values:
              values: ['pending', 'shipped', 'delivered', 'cancelled']
      - name: created_at
        description: Order creation timestamp
        data_tests:
          - not_null
      - name: updated_at
        description: Last update timestamp
        data_tests:
          - not_null

  - name: order_items
    description: Items in orders
    columns:
      - name: id
        description: Order item ID
        data_tests:
          - not_null
          - unique
      - name: order_id
        description: Reference to order
        data_tests:
          - not_null
      - name: product_id
        description: Reference to product
        data_tests:
          - not_null
      - name: quantity
        description: Quantity ordered
        data_tests:
          - not_null

  - name: marketing_spend
    description: Marketing campaign spend data
    columns:
      - name: campaign_id
        description: Campaign identifier
        data_tests:
          - not_null
      - name: campaign_name
        description: Campaign name
        data_tests:
          - not_null
      - name: date
        description: Campaign date
        data_tests:
          - not_null
      - name: platform
        description: Marketing platform
        data_tests:
          - not_null
          - accepted_values:
              values: ['Facebook', 'Google', 'LinkedIn']
      - name: spend
        description: Campaign spend amount
        data_tests:
          - not_null
      - name: clicks
        description: Number of clicks
        data_tests:
          - not_null
      - name: impressions
        description: Number of impressions
        data_tests:
          - not_null
